name: NugetPublish
on:
  push:
    branches:
      - dev2
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generating project version
        uses: EduardSergeev/project-version-action@v6
        with:
            version-file: Omnicasa.OscClient/Omnicasa.OscClient.csproj
            version-stub: '65534.65534.65534.65534'

      - name: Set version for project
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.3
        with:
          file: "Omnicasa.Analyzers.nuspec"
          version: ${{ env.VERSION }}
          
      # Publish
      - name: Publish on version change
        id: publish_nuget
        uses: linch90/publish-nuget@v1.0.2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Omnicasa.Analyzers.nuspec

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://api.nuget.org

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          VERSION_STATIC: ${{env.VERSION}}
