name: NugetPublish
on:
  push:
    branches:
      - dev2
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generating project version
        uses: EduardSergeev/project-version-action@v6
        with:
            version-file: Omnicasa.Analyzer/Omnicasa.Analyzers.csproj
            version-stub: '65534.65534.65534.65534'

      - name: Set version for project
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.3
        with:
          file: "Omnicasa.Analyzers.nuspec"
          version: ${{ env.VERSION }}
          
      # Publish
      - name: Build nuget pack
        run: nuget pack

      - name: Tag vesion
        run: |
          git tag v${{env.VERSION}}
          git push origin v${{env.VERSION}}

      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
